---
- name: Playbook Prepare all nodes
  hosts: aapservers
  gather_facts: true
  vars:
    aap_vip: 10.0.0.94
    db_vip: 10.112.62.25
  roles:
    #- subscription
    - common
    - firewalld
    - ntp
    - ssh

- name: Install HAProxy and Keepalived LoadBalancer nodes
  hosts: Loadbalancer
  gather_facts: true
  vars:
    aap_vip: 10.0.0.94
  roles:
    - keepalived
    - haproxy

- name: Install AAP on Controller play as a control node
  hosts: "{{ groups['controller'][0] }}"
  gather_facts: true
  roles:
    - aap-2.5_install
    - setup
