---
- name: Playbook Prepare all nodes
  hosts: aapservers
  gather_facts: true
  vars:
<<<<<<< HEAD
    aap_vip: 10.0.0.94
    db_vip: 10.112.62.25
=======
    aap_vip: 10.0.0.120
    db_vip: 10.112.63.122
>>>>>>> 6397fa1 (add job template for test AAP with RbbitMQ)
  roles:
    #- subscription
    - common
    - firewalld
    - ntp
    - ssh
<<<<<<< HEAD

- name: Install HAProxy and Keepalived LoadBalancer nodes
  hosts: Loadbalancer
  gather_facts: true
  vars:
    aap_vip: 10.0.0.94
  roles:
    - keepalived
    - haproxy

- name: Install AAP on Controller play as a control node
  hosts: "{{ groups['controller'][0] }}"
  gather_facts: true
  roles:
    - aap-2.5_install
=======
    - aap-2.5_install

- name: Install HAProxy and Keepalived LoadBalancer nodes
  hosts: Loadbalancer
  gather_facts: true
  vars:
    aap_vip: 10.0.0.120
  roles:
    - keepalived
    - haproxy

- name: Install AAP on Controller play as a control node
  hosts: "{{ groups['controller'][0] }}"
  gather_facts: true
  roles:
>>>>>>> 6397fa1 (add job template for test AAP with RbbitMQ)
    - setup
