---
- name: Playbook check servers details
  hosts: localhost
  gather_facts: true
  tasks:
    - name: check os name
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'

    - name: Show var
      debug:
        var: "{{ ansible_facts['hostname'] }}" 
