---
- name: Playbook to check VM details
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display VM system details
      debug:
        msg: "Hostname: {{ ansible_facts['hostname'] }}"

    - name: Display VM system details
      debug:
        msg: "OS Distribution: {{ ansible_facts['distribution'] }}"

    - name: Display VM system details
      debug:
        msg: "Architecture: {{ ansible_facts['architecture'] }}"

    - name: Display VM system details
      debug:
        msg: "Kernel Version: {{ ansible_facts['kernel'] }}"
          
