---
- name: Playbook to check VM details
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display VM system details
      debug:
        msg: |
          Hostname: {{ ansible_facts['hostname'] }}
          OS Distribution: {{ ansible_facts['distribution'] }}
          OS Version: {{ ansible_facts['distribution_version'] }}
          Architecture: {{ ansible_facts['architecture'] }}
          Kernel Version: {{ ansible_facts['kernel'] }}
