---
- name: Display VM creation form data
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "{{ vm_name | default('undefined') }}"
    vm_os: "{{ vm_os | default('undefined') }}"
    vm_flavor: "{{ vm_flavor | default('undefined') }}"
    cloud_init: "{{ cloud_init | default('undefined') }}"

  tasks:
    - name: Show VM Name
      debug:
        msg: "VM Name: {{ vm_name }}"
        
    - name: Show OS Name
      debug:
        msg: "OS: {{ vm_os }}"

    - name: Show Flavor
      debug:
        msg: "Flavor: {{ vm_flavor }}"

    - name: Show Cloud init
      debug:
        msg: "{{ cloud_init }}"
