---
- name: Display VM creation form data
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "{{ vm_name | default('undefined') }}"
    vm_os: "{{ vm_os | default('undefined') }}"
    vm_flavor: "{{ vm_flavor | default('undefined') }}"
    cloud_init: "{{ cloud_init | default('undefined') }}"

  tasks:
    - name: Show VM configuration
      debug:
        msg: |
          VM Name: {{ vm_name }}
          OS: {{ vm_os }}
          Flavor: {{ vm_flavor }}
          Cloud Init:
          {{ cloud_init }}
