---
# tasks file for keepalived
- name: Install Keepalived
  ansible.builtin.yum:
    name: keepalived
    state: present

- name: Backup the original keepalived.conf file
  ansible.builtin.copy:
    src: /etc/keepalived/keepalived.conf
    dest: /etc/keepalived/keepalived.conf.bak
    remote_src: yes


- name: Fix Keeaplived MASTER config.
  ansible.builtin.template:
    src: master.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == groups['gateway'][0]
  notify: restart keepalived

- name: Fix Keeaplived BACKUP config.
  ansible.builtin.template:
    src: backup.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == groups['gateway'][1]
  notify: restart keepalived
      
- name: Start and enable Keepalived service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: keepalived
    enabled: true
